import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import ParticlesBackground from "./component/particle/particle"
import  StoreProvider  from "./StoreProvider"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
    <html lang="en">
      <body className="font-kanit " style={{position:"relative",margin:0,padding:0,background: 'rgb(14,0,103)', background: 'linear-gradient(120deg, rgba(14,0,103,1) 34%, rgba(95,197,255,1) 100%)'}}>
      <ParticlesBackground /> 
      <div class="flex justify-center items-center w-[100%] h-[100vh] ">
      <div class="w-[80vw] h-[90vh] custom-bg-color shadow-[2px_0px_93px_-22px_rgba(110,110,110,0.79)] flex flex-col border-2">

        <Navbar />
        {children}
        
        </div>
        </div></body>
    </html>
    </StoreProvider>
  );
}
